ARG NODE_VERSION=23-alpine
FROM node:${NODE_VERSION} AS base

RUN apk update
RUN apk add --no-cache \
  libc6-compat \
  && rm -rf /var/cache/apk/*

WORKDIR /app

###################
FROM base AS build

COPY package*.json ./

RUN npm ci --production

###################
FROM base AS development

COPY package*.json ./

RUN npm ci

COPY . .

EXPOSE 3000

CMD ["npm", "start"]

###################
FROM nginx:alpine AS production

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]