version: "3.9"

services:
  db:
    image: mariadb:10.6
    container_name: Maria_DB
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
    container_name: login_back
    environment:
      Google_Auth: ${Google_Auth}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_database: ${DB_database}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      APIURL: ${APIURL}
      WEBURL: ${WEBURL}
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    command: npm start

  frontend:
    build:
      context: ./frontend
    container_name: login_front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start

volumes:
  db_data:
