ARG NODE_VERSION=23-alpine
FROM node:${NODE_VERSION} AS base

RUN apk update
RUN apk add --no-cache \
    libc6-compat \
    && rm -rf /var/cache/apk/*

WORKDIR /app

###################
FROM base AS build

COPY package*.json ./

RUN npm ci

###################
FROM base AS development

COPY --from=build /app/node_modules ./node_modules
COPY server.js ./

EXPOSE 3000

CMD ["node", "server.js"]