# Use Node.js base image
FROM node:20.17.0

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 5000

# Start the backend server
CMD ["node", "server.js"]
